name: CI
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  docs:
    runs-on: ubuntu-latest
    name: vimdoc
    steps:
      - uses: actions/checkout@v3
      - uses: kdheepak/panvimdoc@main
        with:
          vimdoc: feline
          pandoc: USAGE.md
          version: "NVIM 0.9.0+"
          toc: true
          treesitter: true
          dedupsubheadings: false
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore(docs): auto-generate vimdoc"
          branch: ${{ github.head_ref }}

  release-please:
    runs-on: ubuntu-latest
    needs:
      - docs
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          package-name: feline
