name: CI
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: panvimdoc
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: feline
          pandoc: USAGE.md
          version: "Neovim >= 0.9.0"
          treesitter: true
          dedupsubheadings: false
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore(build): auto-generate vimdoc"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"

  release-please:
    runs-on: ubuntu-latest
    needs:
      - docs
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: go
          package-name: swaybar
